### ISSUE TITLE
High Server Load issue when playing with 3-5 player 

### ISSUE THREAD

**Issue by fhazal** [mbround18/enshrouded-docker#11]
<img width="290" alt="Screenshot 2024-02-29 163903" src="https://github.com/mbround18/enshrouded-docker/assets/15804741/b226ec2f-ed56-45d7-ad95-a8d2218eda9f">

this is my server spec, im running the server on Ubuntu Server 22.04. 

OS: Ubuntu 22.04.4 LTS x86_64
Kernel: 6.5.0-21-generic
Uptime: 22 hours, 28 mins
Shell: bash 5.1.16
CPU: Intel Xeon E5-2680 v4 (28) @ 3.300GHz
GPU: NVIDIA Quadro K2000
Memory: 20082MiB / 64207MiB

when i play with 3-5 friend i always receive server load yellow and when many activities always got server load red, how can i fix this ? how do i setup and configure the server to utilize and optimize with my server spec? is there any solutions to do that ?

and im using docker-compose up -d to run the dedicated server in the background, so it can run 24/7 even when i close the putty. Is it going to to cause me any problems?

i use root to docker-compose up , should i change to user? please advice the proper way to install and run docker-compose for this dedicated server.

**Comment by mbround18** [comment]
unfortunately this would be on the devs of enshrouded as this container launches their executable

**Comment by mbround18** [comment]
Closing issue
