### ISSUE TITLE
server configuration is overwritten on startup

### ISSUE THREAD

**Issue by ekauz** [mbround18/enshrouded-docker#14]
It seems like the `enshrouded_server.json` config is getting overwritten on startup regardless of whether the file exists or not.
This leads all of the settings, specifically the password, getting reset whenever the container restarts.

Unable to mount just the config as `ro` because it is inside of the parent bind mount.

My only workaround right now is to copy my config over the default-initialized one once the container starts and before the server actually starts up.

**Comment by mbround18** [comment]
oooo good catch! let me look into this!

**Comment by mbround18** [comment]
@ekauz they changed the config format, i got an update for it on #15 :)

**Comment by mbround18** [comment]
https://github.com/mbround18/enshrouded-docker/releases/tag/v1.1.0 should be good go :)

**Comment by ekauz** [comment]
config merges now, looks like it works, thanks!

**Comment by trankillity** [comment]
Just looping back on this - I've just set this container up for the first time and it's also overwriting on every start for me. Cannot get any changes made to stick.
