### ISSUE TITLE
port 15637 should be udp in docker-compose

### ISSUE THREAD

**Issue by Nightreaver** [mbround18/enshrouded-docker#2]
as descriptions sais, port 15637 should be set to udp (`- "15637:15637/udp"`) for the server to work

**Comment by mbround18** [comment]
RCON protocol is TCP https://developer.valvesoftware.com/wiki/Source_RCON_Protocol
Where as Query uses UDP.

Ideally, i can update it to reflect those configurations:

```yaml
    ports:
      - "15636:15636/udp"
      - "15636:15636/tcp"
      - "15637:15637/udp"
      - "15637:15637/tcp"
```

**Comment by Nightreaver** [comment]
If I check with netstat, i dont really seen that many opened ports

**Comment by bandithak** [comment]
Thanks, this fixed for me on Linux. Didn't realize it needed to be so specific.
