### ISSUE TITLE
services.enshrouded.build Additional property platforms is not allowed

### ISSUE THREAD

**Issue by mr-gosh** [mbround18/enshrouded-docker#4]
During Start of the container i get an:

`services.enshrouded.build Additional property platforms is not allowed`

when i comment out the platform stuff the server starts...

**Comment by mbround18** [comment]
That might be a difference in our docker engines, mines most recent. what version are you running?

**Comment by mbround18** [comment]
no response

**Comment by mr-gosh** [comment]
> That might be a difference in our docker engines, mines most recent. what version are you running?

Mine is:
# Docker version 24.0.5, build 24.0.5-0ubuntu1~20.04.1
