### ISSUE TITLE
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1371

### ISSUE THREAD

**Issue by fhazal** [mbround18/enshrouded-docker#8]
`enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1371
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1373
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1375
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1380
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1382
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1384
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1386
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1388
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1390
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1392
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1394
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1396
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1398
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1400
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1402
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1404
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1406
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1408
enshrouded-1  | [ecss] Stats:  Upd:3,360  (17.9ms)  Time:60,008ms  Total:47,989ms  Max:18ms  Avg:14.3ms  +:0  -:0  Ent:5,870  Pred:0
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1416
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1418
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1420
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1422
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1424
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1427
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1445
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1447
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1449
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1457
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1459
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1461
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1464
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1467
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1469
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1471
enshrouded-1  | [ecss] Could not add component e3b96393 for entity 1473
`
this is how i setup my docker compose 

services:
  enshrouded:
    image: mbround18/enshrouded-docker:latest
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    environment:
      SERVER_NAME: "Bajubesi Enshrouded Server" # Optional, Name of the server
      PASSWORD: "mypasswd" # Optional, Password for the server
    #      SAVE_DIRECTORY: ./savegame # Optional, Save directory for the game
    #      LOG_DIRECTORY: ./logs # Optional, Log directory for the server
    #      SERVER_IP: 0.0.0.0 # Optional, IP address for the server
    #      GAME_PORT: 15636 # Optional, Game port for the server
    #      QUERY_PORT: 15637 # Optional, Query port for the server
    #      SLOT_COUNT: 16 # Optional, Number of slots for the server
    ports:
      - "15636:15636/udp"
      - "15636:15636/tcp"
      - "15637:15637/udp"
      - "15637:15637/tcp"
    volumes:
      - ./data:/home/steam/enshrouded
  backups:
    image: mbround18/backup-cron:latest
    environment:
      - SCHEDULE=*/10 * * * *
      - INPUT_FOLDER=/home/steam/enshrouded/savegame
      - OUTPUT_FOLDER=/home/steam/backups
      - OUTPUT_USER=1000
      - OUTPUT_GROUP=1000
      - RETAIN_N_DAYS=5
    volumes:
      - ./data:/home/steam/enshrouded
      - ./backups:/home/steam/backups
    restart: unless-stopped

**Comment by mbround18** [comment]
That looks good, what kind of processor are you using?

**Comment by fhazal** [comment]
> That looks good, what kind of processor are you using?
 root@HPZ440-Server
      
OS: Ubuntu 22.04.4 LTS x86_64
Kernel: 6.5.0-21-generic
Uptime: 22 hours, 28 mins
Shell: bash 5.1.16
CPU: Intel Xeon E5-2680 v4 (28) @ 3.300GHz
GPU: NVIDIA Quadro K2000
Memory: 20082MiB / 64207MiB
