### ISSUE TITLE
server not visible in game if using auto backup docker compose 

### ISSUE THREAD

**Issue by fhazal** [mbround18/enshrouded-docker#9]
i try using the default auto back up docker compose https://github.com/mbround18/enshrouded-docker/blob/main/docs/compose-with-backups.md and use docker compose up seems like the server online but i can't find the server when using search with my server name,the server is not visible in game, how should i code the docker-compose.yml ?

**Comment by mbround18** [comment]
https://github.com/mbround18/enshrouded-docker/pull/10

**Comment by fhazal** [comment]
> #10 adding the specific port configurations should fix that

tq so much for this, it's working now with back up
